language: python
sudo: false

#branches:
#  only: 
#    - master

before_install:
  - pip install -U pip wheel
  - pip install flake8
  - pip install autopep8

install:
  - python setup.py sdist
  - python install dist/*.tar.gz

script:
  #- flake8
  #- autopep8
  - python -m unittest discover ./tests